use_frameworks!

platform :ios, '9.0'

target 'HBSDCycleScrollView_Example' do
  pod 'HBSDCycleScrollView', :path => '../'

  target 'HBSDCycleScrollView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
